config/routes.rb
Rails.application.routes.draw do
  root 'pages#dashboard'

  devise_for :users

  patch '/language/:locale', to: 'application#language', as: :language

  devise_scope :user do
    get 'log_in' => 'devise/sessions#new'
  end

  scope "/admin" do
    resources :users do
      collection do
        get :new_admin
        post :create_admin
        get :customers
        get :admins
        get :query
      end
    end
  end

  resources :projects do
    collection do
      get :canceled
      get :query
    end

    member do
      patch :complete, as: :complete
      patch :uncomplete, as: :uncomplete
      patch :cancel
      patch :uncancel
    end
  end

  resources :notices
  resources :attachments
  resources :documents

  get '/dashboard' => 'pages#dashboard'
  get '/admin' => 'pages#dashboard_admin'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:login]
  validates :username, uniqueness: { case_sensitive: false }
  has_many :projects

  attr_accessor :login

  include PgSearch

  # Padrões de pesquisa:
  # Pesquisa pelo :name e :username, :contact_name e :email
  pg_search_scope :search, against: [:name, :username, :contact_name, :email] 

  # Verifica se o usuário é administrador
  def is_admin?
    admin
  end

  # Verifica se o usuário possui algum projeto ativo
  # * A função pára no primeiro projeto que estiver incompleto
  # * Caso não haja projetos incompletos, retorna +false+
  def has_any_active_project?
    self.projects.each { |project| return true if project.uncompleted? || !project.canceled? }
    false
  end  

  # método da gem pg_search
  def self.text_search(query)
    if query.present?
      search(query)
    end
  end

  # Verifica se :project pertence ao usuário
  def has_project(project)
    self.projects.include?(project)
  end

  # Override da função do Devise para que seja possível fazer login
  # tanto com email quanto com usuário
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  layout "dashboard"
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # def new
  #   super
  # end

  # def create
  #   super
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "dashboard"

  before_action :load_user, only: [:show, :edit, :update]
  before_action :admin_only, except: [:edit, :update]
  
  # GET
  # Lista todos os usuários
  def index
    @users = User.all.page(params[:page]).per_page(10)
  end

  # Carrega o usuário e salva seu ID caso seja necessário adicionar
  # um projeto pertencente ele depois
  def show
    session[:user_id] = params[:id]
  end

  # GET
  # Instancia um novo usuário
  def new
    @user = User.new
  end

  # POST
  # Gera uma senha aleatória que é atribuída ao usuário
  # Caso o usuário seja salvo no banco de dados com sucesso, um email é 
  # enviado ao email cadastrado contendo seu login e sua senha
  def create
    generated_password = Devise.friendly_token.first(8)
    @user = User.new(user_params(generated_password))
    if @user.save
      UserMailer.new_user_mail(@user, generated_password).deliver_later
      redirect_to customers_users_path
    else
      render :new
    end
  end

  # GET
  # Carrega usuário para que seja possível editá-lo
  def edit
  end

  # PATCH
  # Atualiza os atributos do usuário
  def update
    if @user.update_attributes(user_params)
      redirect_to users_url
    else
      render :edit
    end
  end

  # GET
  # Carrega todos os usuários que não são administradores, ou seja, clientes
  def customers
    @users = User.where(admin: false).page(params[:page]).per_page(10)
  end

  # GET
  # Carrega todos os usuários administradores
  def admins
    @users = User.where(admin: true).page(params[:page]).per_page(10)
  end

  # GET
  # Instancia um novo usuário
  # Ao clicar no botão da página, o método chamado será o :create_admin
  def new_admin 
    @user = User.new  
  end

  # POST
  # Método chamado na view da ação :new_admin
  # Gera uma senha aleatória e a atribui ao usuário. Após isso, o campo 
  # administrador desse usuário é setado para TRUE.
  # Caso o novo administrador seja salvo com sucesso, um email será
  # enviado informando-o de seu novo login e senha.
  def create_admin
    generated_password = Devise.friendly_token.first(8)
    @user = User.new(user_params(generated_password))
    @user[:admin] = true
    if @user.save
      UserMailer.new_user_mail(@user, generated_password).deliver_later
      redirect_to root_path
    else
      render "new"
    end
  end

  # GET
  # Procura nos usuários e seus relacionados(projetos) pelo(s) termo(s) pesquisado(s)
  def query
    query = params[:query]

    if query.present?
      @users = User.text_search(query).page(params[:page]).per_page(10)
    else
      @users = nil
    end
  end

  private
  # Carrega usuário a partir do ID
  def load_user
    @user = User.find(params[:id])
  end

  # Strong params
  # A senha é carregada nos parâmetros e então enviada para o usuário para então ser 
  # salvo
  def user_params(password)
    params[:user][:password] = password
    params.require(:user).permit(:username, :name, :contact_name, :phone, :email,
                                 :password)
  end

  # Checa se o usuário é administrador, caso contrário é levado a raiz do sistema.
  def admin_only
    redirect_to root_path, notice: t('alerts.admin_privileges') unless current_user.is_admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index_all.html.erb
<div class="text-center">
  <%= form_tag query_users_path, method: :get do %>
    <p>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag t('buttons.search'), name: nil, class: "btn btn-primary" %>
    </p>
  <% end %>
</div>

<h3 class="text-center"><%= t('table.all_users') %></h3>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <th><%= t('user.name') %></th>
      <th><%= t('user.username') %></th>
      <th><%= t('user.email') %></th>
      <th><%= t('user.type') %></th>
      <th><%= t('table.active_projects') %></th>
      <th><%= t('table.projects') %></th>
    </thead>
    <tbody>
      <% if @users %>
        <% @users.each do |user| %>
          <% projects = user.projects %>
          <tr class=<%= "border-left-green" if user.has_any_active_project? %>>
            <td><%= link_to user.name, user_path(user) %></td>
            <td><%= link_to user.username, user_path(user) %></td>
            <td><%= user.email %></td>
            <td><%= user.is_admin? ? t('user.admin') : t('user.common') %></td> 
            <td><%= user.projects.where(completed: false).length %> </td>     
            <td><%= user.projects.length %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @projects, class: "text-center" if @users %>
</div>



<div class="text-center">
  <%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
</div>

app/views/users/admins.html.erb
<h3 class="text-center"><%= t('table.admin_list') %></h3>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <th><%= t('user.name') %></th>
      <th><%= t('user.username') %></th>
      <th><%= t('user.email') %></th>
      <th><%= t('user.phone') %></th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= link_to user.username, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @projects, class: "text-center" %>
</div>
<div class="text-center">
  <%= link_to t('buttons.home'), root_path, class:"btn btn-primary" %>
</div>

app/views/users/customers.html.erb
<h3 class="text-center"><%= t('table.client_list') %></h3>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <th><%= t('user.name') %></th>
      <th><%= t('user.username') %></th>
      <th><%= t('user.email') %></th>
      <th><%= t('user.phone') %></th>
      <th><%= t('user.contact_name') %></th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr class="<%= "border-left-green" if user.has_any_active_project? %>">
          <td><%= link_to user.name, user_path(user) %></td>
          <td><%= link_to user.username, user_path(user) %></td>
          <td><%= user.email %></td>
          <td><%= user.phone %></td>
          <td><%= user.contact_name %></td>
        </tr>        
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @projects, class: "text-center" %>
</div>
<div class="text-center">
  <%= link_to t('buttons.home'), root_path, class:"btn btn-primary" %>
</div>

app/views/users/index.html.erb
<%= render 'index_all' %>

app/views/users/new.html.erb
<div class="container">
  <div class="row ">
      <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title text-center"><%= t('user.client_register') %></h3>
          </div>
          <div class="panel-body">
            <%= form_for @user do |f| %>
              <div class="form-group">
                <%= f.label :username, t('user.username'), class: "text-center" %><br />
                <%= f.text_field :username, autofocus: true, class: "form-control" %>
              </div>
              
              <div class="form-group">
                <%= f.label :name, t('user.name'), class: "text-center" %><br />
                <%= f.text_field :name, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :email, t('user.email') , class: "text-center" %><br />
                <%= f.email_field :email, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :contact_name, t('user.contact_name'), class: "text-center" %><br />
                <%= f.text_field :contact_name, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :phone, t('user.phone'), class: "text-center" %><br />
                <%= f.text_field :phone, class: "form-control" %>
              </div>

              <div class="actions">
                <%= f.submit t('buttons.create'), class: "btn btn-lg btn-success btn-block" %>
              </div>
            <% end %>
          </div>
        </div>
        <p class="text-center"><%= link_to t('buttons.home'), root_path, class: "btn btn-primary text" %></p>
      </div>
  </div>
</div>

app/views/users/new_admin.html.erb
<div class="container">
  <div class="row ">
      <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title text-center"><%= t('user.admin_register') %></h3>
          </div>
          <div class="panel-body">
            <%= form_for @user, url: {action: "create_admin"}, method: :post do |f| %>
              <div class="form-group">
                <%= f.label :username, t('user.username'), class: "text-center" %><br />
                <%= f.text_field :username, autofocus: true, class: "form-control" %>
              </div>
              
              <div class="form-group">
                <%= f.label :contact_name, t('user.contact_name'), class: "text-center" %><br />
                <%= f.text_field :contact_name, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :phone, t('user.phone'), class: "text-center" %><br />
                <%= f.text_field :phone, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= f.label :email, t('user.email'), class: "text-center" %><br />
                <%= f.email_field :email, class: "form-control" %>
              </div>

              <div class="actions">
                <%= f.submit t('buttons.create'), class: "btn btn-lg btn-success btn-block" %>
              </div>
            <% end %>
          </div>
        </div>
        <p class="text-center"><%= link_to t('buttons.home'), root_path, class: "btn btn-primary text" %></p>
      </div>
  </div>
</div>

app/views/users/query.html.erb
<%= render 'index_all' %>

app/views/users/show.html.erb
<div class="container">
  <%= link_to t('user.create_project', name: @user.username), new_project_path, class: "btn btn-success pull-right" %>
  <div class="row">
    <div class="well">
      <p><span class="small"><%= t('user.name') %></span>:<b> <%= @user.name %></b></p>
      <p><span class="small"><%= t('user.email') %></span>:<b> <%= @user.email %></b></p>
      <p><span class="small"><%= t('user.phone') %></span>:<b> <%= @user.phone %></b></p>
    </div>      
  </div>

  <h3><%= t('table.projects') %></h3>

  <div class="table-responsive">
    <% if @user.projects.empty? %>
      <p class="text-center"><%= t('project.empty') %></p>
    <% else %>
      <table class="table table-striped">
        <thead>
          <th><%= t('table.project') %></th>
          <th><%= t('table.status') %></th>
        </thead>
        <tbody>
          <% @user.projects.each do |project| %>
            <% if project.completed? %>
              <tr>
                <td><%= link_to project.name, project_path(project) %></td>   
                <td class="btn-success"><%= t('project.completed') %></td>
              </tr>
            <% elsif project.canceled? %>
              <tr>
                <td><%= link_to project.name, project_path(project) %></td>    
                <td class="btn-danger"><span ><%= t('project.canceled') %></span></td>  
              </tr>
            <% else %>
              <tr>
                <td><%= link_to project.name, project_path(project) %></td>
                <td class="btn-primary"><%= t('project.in_progress') %></td> 
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

  <%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
</div>