config/routes.rb
Rails.application.routes.draw do
  root 'pages#dashboard'

  devise_for :users

  patch '/language/:locale', to: 'application#language', as: :language

  devise_scope :user do
    get 'log_in' => 'devise/sessions#new'
  end

  scope "/admin" do
    resources :users do
      collection do
        get :new_admin
        post :create_admin
        get :customers
        get :admins
        get :query
      end
    end
  end

  resources :projects do
    collection do
      get :canceled
      get :query
    end

    member do
      patch :complete, as: :complete
      patch :uncomplete, as: :uncomplete
      patch :cancel
      patch :uncancel
    end
  end

  resources :notices
  resources :attachments
  resources :documents

  get '/dashboard' => 'pages#dashboard'
  get '/admin' => 'pages#dashboard_admin'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :notices
  belongs_to :user

  include PgSearch

  # Padrões de pesquisa:
  # Pesquisa pelo :name e :description da notícia
  # Pesquisa pelos modelos associados
  pg_search_scope :search, against: [:name, :description],
                  associated_against: {user: [:name, :username, :contact_name, :email]}

  # Retorna true caso o projeto esteja completo
  # Retorna false caso contrário
  def completed?
    self.completed
  end

  # Retorna true caso o projeto esteja incompleto
  # Retorna false caso contrário
  def uncompleted?
    !self.completed
  end

  # Retorna true caso o projeto tenha sido cancelado
  # Retorna false caso contrário
  def canceled?
    self.canceled
  end

  # Método da gem pg_search
  def self.text_search(query)
    if query.present?
      search(query)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout "dashboard"
  before_action :load_project, only: [ :show, :edit, :update, :destroy, :complete, 
                                      :uncomplete, :cancel, :uncancel ]

  before_action :admin_only, except: [:show]
  before_action :check_user, only: [:show]

  # GET
  # Lista todos os projetos
  # Caso admin, lista todos
  # Caso usuário comum, lista apenas os próprios
  def index
    if current_user.is_admin?
      @projects = Project.order("created_at DESC").page(params[:page]).per_page(10)
    else
      @projects = current_user.projects.order("created_at DESC")
    end  
  end

  # GET
  # Insere na sessão o ID do projeto
  # Carrega as notícias referentes ao projeto
  def show
    redirect_to root_path if @project.nil?
    session[:project_id] = params[:id]
    @notices = @project.notices.order("created_at DESC")
  end

  # GET
  # Instancia um novo projeto
  def new
    @project = Project.new
  end

  # GET
  # Cria um novo projeto
  # Associa o projeto ao usuário a partir do :user_id salvo na sessão ao entrar
  # na página do usuário
  def create
    @project = Project.new(project_params)
    @project[:user_id] = session[:user_id]
    if @project.save
      redirect_to root_path
    else
      render "new"
    end
  end

  # GET
  # Página para editar um projeto
  def edit
  end

  # PATCH
  # Atualiza o projeto
  def update
    if @project.update(project_params)
      redirect_to root_path
    else
      render "edit"
    end
  end

  #NUNCA USAR *********************************
  # Apaga, permanentemente, o projeto
  def destroy
    if @project.destroy
      redirect_to root_path
    else
      redirect_to root_path
    end
  end
  # *******************************************

  # GET
  # Lista os projetos que estão completos
  def complete
    @project.update_attribute(:completed, true)
    redirect_to project_path(@project)
  end

  # GET
  # Lista os projetos que não estão completos
  def uncomplete
    @project.update_attribute(:completed, false)
    redirect_to project_path(@project)
  end


  # Lista os projetos cancelados
  def canceled
    @projects = Project.where(canceled: true)
  end

  # PATCH
  # Cancela o projeto
  def cancel
    @project.update_attribute(:canceled, true)
    redirect_to project_path(@project)
  end

  # PATCH
  # Descancela o projeto
  def uncancel 
    @project.update_attribute(:canceled, false)
    redirect_to project_path(@project)
  end

  # GET
  # Procura nos projetos e notícias relacionadas o(s) termos(s) procurado(s)
  def query
    query = params[:query]

    if query.present?
      @projects = Project.text_search(query).page(params[:page]).per_page(10)
    else
      @projects = nil
    end
  end

  private
    # Strong Parameters
    def project_params
      params.require(:project).permit(:name, :description)
    end

    # Pega os parametros para carregar o projeto do banco de dados
    def load_project
      @project = Project.find(params[:id])
    end

    # Checa se o projeto pertence ao usuário. Caso contrário é levado a raiz
    # do sistema
    def check_user
      redirect_to root_path, notice: t('alerts.admin_privileges') unless current_user.has_project(@project) || current_user.is_admin?
    end

    # Checa se o usuário é administrador. Caso contrário é levado a raiz do
    # sistema
    def admin_only
      redirect_to root_path, notice: t('alerts.admin_privileges') unless current_user.is_admin?
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_index_all.html.erb
<div class="text-center">
  <%= form_tag query_projects_path, method: :get do %>
    <p>
      <%= text_field_tag :query, params[:query] %>
      <%= submit_tag t('buttons.search'), name: nil, class: "btn btn-primary" %>
    </p>
  <% end %>
</div>

<h3 class="text-center"><%= t('table.all_projects') %></h3>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <th><%= t('table.project') %></th>
      <th><%= t('table.client') %></th>
      <th><%= t('table.status') %></th>
    </thead>
    <tbody>
      <% if @projects %>
        <% @projects.each do |project| %>
          <% if project.completed? %>
            <tr>
              <td><%= link_to project.name, project_path(project) %></td> 
              <td><%= link_to project.user.name, user_path(project.user) %></td>     
              <td class="btn-success"><%= t('project.completed') %></td>
            </tr>
          <% elsif project.canceled? %>
            <tr>
              <td><%= link_to project.name, project_path(project) %></td>    
              <td><%= link_to project.user.name, user_path(project.user) %></td>     
              <td class="btn-danger"><span ><%= t('project.canceled') %></span></td>  
            </tr>
          <% else %>
            <tr>
              <td><%= link_to project.name, project_path(project) %></td>
              <td><%= link_to project.user.name, user_path(project.user) %></td>     
              <td class="btn-primary"><%= t('project.in_progress') %></td> 
            </tr>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @projects, class: "text-center" if @users %>
</div>
<div class="text-center">
  <%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
</div>

app/views/projects/edit.html.erb
<div class="container">
  <div class="row ">
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title text-center"><%= t('buttons.edit') %></h3>
        </div>
        <div class="panel-body">
          <%= form_for @project do |f| %>
            <div class="form-group">
              <%= f.label :name, t('project.name') , class: "text-center" %><br />
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
            
            <div class="form-group">
              <%= f.label :description, t('project.description'), class: "text-center" %><br />
              <%= f.text_area :description, class: "form-control" %>
            </div>

            <div class="actions">
              <%= f.submit t('buttons.edit'), class: "btn btn-lg btn-success btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
      <p class="text-center">
      <div class="text-center">
        <%= link_to t('buttons.back'), user_path(session[:user_id]), class: "btn btn-primary text" %>
        <%= link_to t('buttons.home'), root_path, class: "btn btn-primary text" %></p>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<%= render 'index_all' %>

app/views/projects/new.html.erb
<div class="container">
  <div class="row ">
    <div class="col-md-4 col-md-offset-4">
      <div class="login-panel panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title text-center"><%= t('project.create') %></h3>
        </div>
        <div class="panel-body">
          <%= form_for @project do |f| %>
            <div class="form-group">
              <%= f.label :name, t('project.name') , class: "text-center" %><br />
              <%= f.text_field :name, autofocus: true, class: "form-control" %>
            </div>
            
            <div class="form-group">
              <%= f.label :description, t('project.description'), class: "text-center" %><br />
              <%= f.text_area :description, class: "form-control" %>
            </div>

            <div class="actions">
              <%= f.submit t('buttons.create_project'), class: "btn btn-lg btn-success btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
      <p class="text-center">
      <div class="text-center">
        <%= link_to t('buttons.back'), user_path(session[:user_id]), class: "btn btn-primary text" %>
        <%= link_to t('buttons.home'), root_path, class: "btn btn-primary text" %></p>
      </div>
    </div>
  </div>
</div>

app/views/projects/query.html.erb
<%= render 'index_all' %>

app/views/projects/show.html.erb
<h3>
  <%= @project.name %>
    <b><%= t('project.completed') if @project.completed? %></b>
    <b><%= t('project.canceled') if @project.canceled? %></b>
</h3>
<p><%= link_to t('buttons.add_notice'), new_notice_path, class: "btn btn-success pull-right"  if current_user.is_admin? %></p>

<div class="well">
  <p><%= @project.description %></p>  
  <p class="pull-right small"><%= t('project.added_on', date: @project.created_at.to_date) %></p>
</div>
<div class="text-center">
  <h3><%= t('project.notices') %></h3>
</div>
<div class="row">
<% @notices.each do |notice| %>

  <div class="col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <% title = truncate notice.title, length: 50 unless current_user.is_admin? %>
        <% title = truncate notice.title, length: 35 if current_user.is_admin? %>
        <%= link_to title, notice_path(notice) %>
        <% if current_user.is_admin? %>
          <ul class="pull-right inline">
            <li>
              <%= link_to edit_notice_path(notice) do %>
                <span class="glyphicon glyphicon-pencil"></span>
              <% end %>
            </li>
            <li>
              <%= link_to notice_path(notice), method: :delete, data: { confirm: t('project.confirm_delete_notice') } do %>
                <span class="glyphicon glyphicon-remove"></span>
              <% end %>
            </li>
          </ul>
        <% end %>
      </div>
      <div class="panel-body">
        <p><%= truncate notice.description, length: 100 %></p>
      </div>
      <div class="panel-footer">
        <%= link_to t('buttons.see_notice'), notice_path(notice) %>
        <ul class="pull-right inline">
          <li><span class="glyphicon glyphicon-picture"></span><%= notice.attachments.empty? ? '0' : notice.attachments.length %></li>
          <li><span class="glyphicon glyphicon-text-size"></span><%= notice.documents.empty? ? '0' : notice.documents.length %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>
</div>

<!-- Links -->
<%= link_to t('buttons.home'), root_path, class: "btn btn-primary" %>
<% if current_user.is_admin? %>
  <%= link_to t('buttons.see_client'), user_path(@project.user), class: "btn btn-primary" %>
  <%= link_to t('buttons.edit'), edit_project_path(@project), class: "btn btn-primary" %>
  <% if @project.uncompleted? %>
    <%= link_to t('buttons.complete'), complete_project_path(@project), method: :patch, class: "btn btn-success", data: { confirm: t('project.confirm_completed') }  if @project.uncompleted? %>
  <% else %>
    <%= link_to t('buttons.uncomplete'), uncomplete_project_path(@project), method: :patch, class: "btn btn-danger", data: { confirm: t('project.confirm_reopen') } if @project.completed? %>
  <% end %>
  <% if @project.canceled? && @project.uncompleted? %>
    <%= link_to t('buttons.reopen'), uncancel_project_path(@project), method: :patch, class: "btn btn-danger pull-right", data: { confirm: t('project.confirm_reopen') } %>
  <% elsif @project.uncompleted? %>
    <%= link_to t('buttons.cancel'), cancel_project_path(@project), method: :patch, class: "btn btn-danger pull-right", data: { confirm: t('project.confirm_cancelation') } %>
  <% end %>
<% end %>