config/routes.rb
Rails.application.routes.draw do
  root 'pages#dashboard'

  devise_for :users

  patch '/language/:locale', to: 'application#language', as: :language

  devise_scope :user do
    get 'log_in' => 'devise/sessions#new'
  end

  scope "/admin" do
    resources :users do
      collection do
        get :new_admin
        post :create_admin
        get :customers
        get :admins
        get :query
      end
    end
  end

  resources :projects do
    collection do
      get :canceled
      get :query
    end

    member do
      patch :complete, as: :complete
      patch :uncomplete, as: :uncomplete
      patch :cancel
      patch :uncancel
    end
  end

  resources :notices
  resources :attachments
  resources :documents

  get '/dashboard' => 'pages#dashboard'
  get '/admin' => 'pages#dashboard_admin'

end

app/views/layouts/_default_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CearáSteel</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="bg-whiteish">
    <div class="notices container-fluid">
      <div class="container">
        <div class="row text-center">
          <p class="notice success"><%= notice %></p>
          <p class="alert danger"><%= alert %></p>
        </div>
      </div>  
          
      <p class="pull-right small"><%= t('buttons.click_to_close') %></p>
    </div>
    
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <!-- Botão responsivo -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to root_url, class: "navbar-brand" do %>
            <b>Ceará</b>Steel
          <% end  %>
        </div>

        <!-- Links do navbar -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <!--  Links à direita -->
          
          <ul class="nav navbar-nav navbar-right">
            <% if current_user.is_admin? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t('menu.actions') %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to t('menu.add_client'), new_user_path %></li>
                  <li><%= link_to t('menu.add_admin'), new_admin_users_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to t('menu.see_clients'), customers_users_path %></li>
                  <li><%= link_to t('menu.see_admins'), admins_users_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to t('menu.all_users'), users_path %></li>
                  <li><%= link_to t('menu.all_projects'), projects_path %></li>
                </ul>
              </li>
            <% end %>
            <% if user_signed_in? %>
              <li><%= link_to t('menu.my_account'), edit_user_registration_path %></li>
              <li><a href=""><b><%= t('menu.logged_as', name: current_user.name) %></b></a></li>
              <li><%= link_to t('menu.logout'), destroy_user_session_path, method: :delete, class: "btn btn-danger white-text"%></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>   
    <div class="container">
      <%= yield %>
    </div>
        
   
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Steel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="bg-whiteish">
  <div class="notices container-fluid">
    <div class="container">
      <div class="row text-center">
        <p class="notice success"><%= notice %></p>
        <p class="alert danger"><%= alert %></p>
      </div>
    </div>  
        
    <p class="pull-right small">Clique para fechar.</p>
  </div>


  <div class="container">
    <%= yield %>
  </div>
  

</body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Steel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

  </body>
</html>

app/views/layouts/dashboard.html.erb
<%= render 'layouts/default_layout' %>

app/views/layouts/devise.html.erb
<%= render 'layouts/default_layout' %>